---
ubtu20cis_rule_3_4_1: false
ubtu20cis_rule_3_4_2: false
ubtu20cis_rule_3_4_3: false
ubtu20cis_rule_3_4_4: false
# ufw
ubtu20cis_rule_3_4_1_1: false
ubtu20cis_rule_3_4_1_2: false
ubtu20cis_rule_3_4_1_3: false
ubtu20cis_rule_3_4_1_4: false
ubtu20cis_rule_3_4_1_5: false
ubtu20cis_rule_3_4_1_6: false
ubtu20cis_rule_3_4_1_7: false

ansible_user: "master"
...
